# Site settings
title: Chance Monnette Photography
header-img: img/home-bg.jpg
email: cmonnette.photo@gmail.com
description: "Freelance Photographer from the Detroit Area"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: chancellorr
github_username:  chancellorr
facebook_username:  chancellorr

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
